name: Docker Image CI

on: [push]

jobs:

  build_imageA:
 
    runs-on: ubuntu-latest
 
    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest
    -
      name: Run Buildx
      run: |
        curl --location https://github.com/aloysbaillet/buildx-testing/suites/244631830/artifacts/67804 -o docker-cache.zip
        unzip docker-cache.zip
        curl --location https://github.com/aloysbaillet/buildx-testing/suites/246317487/artifacts/72270 -o ccache.zip
        unzip ccache.zip
        tar xf ccache/ccache.tar.gz
        # buildx-testing-image-a
        docker buildx build \
          . \
          -t aloysbaillet/buildx-testing-image-a:0 \
          --target=buildx-testing-image-a \
          --cache-from=type=local,src=docker-cache \
          --cache-to=type=local,mode=max,dest=docker-cache-a \
          --load
        # buildx-testing-image-a-ccache
        docker buildx build \
          . \
          --target=buildx-testing-image-a-ccache \
          --platform=local \
          -o .
    -
      name: Upload docker-cache
      uses: actions/upload-artifact@v1
      with:
        name: docker-cache-a
        path: docker-cache-a
    -
      name: Upload ccache
      uses: actions/upload-artifact@v1
      with:
        name: ccache
        path: ccache/ccache.tar.gz

  build_imageB:
 
    runs-on: ubuntu-latest
    needs: build_imageA

    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest
    -
      name: Download docker cache
      uses: actions/download-artifact@v1
      with:
        name: docker-cache-a
    -
      name: Run Buildx
      run: |
        # buildx-testing-image-b
        mkdir ccache
        docker buildx build \
          . \
          -t aloysbaillet/buildx-testing-image-b:0 \
          --target=buildx-testing-image-b \
          --cache-from=type=local,src=docker-cache-a \
          --cache-to=type=local,mode=max,dest=docker-cache-b
          --load
    -
      name: Upload docker-cache
      uses: actions/upload-artifact@v1
      with:
        name: docker-cache-b
        path: docker-cache-b
