name: Docker Image CI

on: [push]

jobs:

  build_imageA:
 
    runs-on: ubuntu-latest
 
    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest
    -
      name: Run Buildx
      run: |
        curl --location https://github.com/aloysbaillet/buildx-testing/suites/244631830/artifacts/67804 -o docker-cache.zip
        unzip docker-cache.zip
        docker buildx build \
          . \
          -f imageA/Dockerfile \
          -t aloysbaillet/buildx-testing-image-a:0 \
          --cache-from=type=local,src=
          --cache-to=type=local,mode=max,dest=docker-cache-a \
          --load
    -
      name: Upload cache
      uses: actions/upload-artifact@v1
      with:
        name: docker-cache-a
        path: docker-cache-a
    -
      name: Save docker image for downstream
      run: docker save aloysbaillet/buildx-testing-image-a:0 | gzip -c > aloysbaillet-buildx-testing-image-a-0.tar.gz
    -
      name: Upload image
      uses: actions/upload-artifact@v1
      with:
        name: docker-image
        path: aloysbaillet-buildx-testing-image-a-0.tar.gz

  build_imageB:
 
    runs-on: ubuntu-latest
    needs: build_imageA

    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest
    -
      name: Download docker cache
      uses: actions/download-artifact@v1
      with:
        name: docker-cache-a
    -
      name: Download docker image
      uses: actions/download-artifact@v1
      with:
        name: docker-image
    -
      name: Run Buildx
      run: |
        gunzip -c docker-image/aloysbaillet-buildx-testing-image-a-0.tar.gz | docker load
        docker buildx build \
          . \
          -f imageB/Dockerfile \
          -t aloysbaillet/buildx-testing-image-b:0 \
          --cache-from=type=local,src=docker-cache-a \
          --cache-to=type=local,mode=max,dest=docker-cache-b \
          --load
