name: Docker Image CI

on: [push]

jobs:

  build_imageA:
 
    runs-on: ubuntu-latest
 
    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest
    -
      name: Run Buildx
      run: |
        docker buildx build \
          . \
          -f imageA/Dockerfile \
          -t aloysbaillet/buildx-testing-image-a:0 \
          --cache-to=type=local,mode=max,dest=docker-cache \
          --load
    -
      name: Upload cache
      uses: actions/upload-artifact@v1
      with:
        name: docker-cache
        path: docker-cache

  build_imageB:
 
    runs-on: ubuntu-latest
    needs: build_imageA

    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@master
      with:
        version: latest
    -
      name: Download docker cache
      uses: actions/download-artifact@v1
      with:
        name: docker-cache
    -
      name: Run Buildx
      run: |
        docker buildx build \
          . \
          -f imageB/Dockerfile \
          -t aloysbaillet/buildx-testing-image-b:0 \
          --cache-to=type=local,mode=max,dest=docker-cache \
          --load
      
